name: CI - Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.13.6
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.6'
          cache: 'pip'

      - name: Verificar versión de Python
        run: python --version

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Mostrar usuario de GitHub
        run: 'echo "Ejecutando pruebas con el usuario: ${{ github.actor }}"'

      - name: Ejecutar tests
        run: pytest ./test_text_lib.py -v -s
